import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STRINGS = {
  en: {
    heroTitle: "Analyze with MIZAN and find the right property",
    heroSub: "The trusted portal to compare and navigate the real estate market in Ethiopia",
    heroUploadCta: "Upload your listing",
    rent: "Rent",
    buy: "Buy",
    sell: "Sell",
    findAgent: "Find an agent",
    manageRentals: "Manage rentals",
    verifyListing: "Verify your listing",
    advertise: "Advertise",
    getHelp: "Get help",
    signIn: "Sign in",
    signOut: "Sign out",
    dashboard: "Dashboard",
    navListings: "Listings",
    navAbout: "About",
    navMap: "Map",
    navUpload: "Upload listing",
    navAdmin: "Admin",
    navLogin: "Login",
    navAccount: "Account",
    navLogout: "Logout",
    menu: "Menu",
    closeMenu: "Close menu",
    openMenu: "Open menu",
    searchBuy: "Buy",
    searchRent: "Rent",
    searchForRent: "For rent",
    searchForSale: "For sale",
    searchPlaceholder: "Search by area or keyword",
    searchType: "Type",
    searchCity: "City",
    searchArea: "Area",
    searchBedrooms: "Bedrooms",
    searchSubmit: "Search",
    moreFilters: "More filters",
    popularSearches: "Popular searches",
    quickFilter1: "Apartments · Bole",
    quickFilter2: "2 bedrooms · for rent",
    quickFilter3: "Villas · for sale",
    quickFilter4: "Commercial · Kazanchis",
    quickFilter5: "Studios · under ETB 50k",
    properties: "Properties",
    listingsCount: "listings",
    loadingListings: "Loading listings…",
    sort: "Sort",
    sortRecommended: "Recommended",
    sortLatest: "Newest",
    sortPriceAsc: "Price: low to high",
    sortPriceDesc: "Price: high to low",
    sortSize: "Size",
    showingPerPage: "Showing {n} per page",
    pageOf: "Page {page} of {total}",
    noListingsTitle: "No listings match these filters",
    noListingsBody: "Try switching between buy and rent, clearing filters, or run a fresh scraper sync.",
    recommendations: "Recommended for you",
    recommendationsSub: "Hand-picked matches — fewer clicks to decide.",
    verified: "Verified",
    newBadge: "New",
    bedrooms: "Bedrooms",
    beds: "Bedrooms",
    baths: "Baths",
    livingArea: "Living area",
    furnishedLabel: "Furnished",
    furnishedYes: "Yes",
    furnishedNo: "No",
    monthlyRentSuffix: "Monthly rent",
    saleSuffix: "Sale",
    salePrice: "Sale price",
    rentPrice: "Rent",
    noPhoto: "No photo",
    cardDisclaimer: "All listings belong to their respective platforms ({source}).",
    viewDetails: "View details",
    compareMode: "Compare",
    compareModeActive: "Selecting…",
    compareModeHint: "Pick 2 listings to compare side by side.",
    compareAdd: "Add to compare",
    compareRemove: "Remove from compare",
    compareSelected: "Selected for compare",
    compareTrayLabel: "Compare selection",
    compareTrayTitle: "{count} of {max} selected",
    compareSlotEmpty: "Select listing",
    compareClear: "Clear",
    compareExit: "Exit",
    compareCta: "Compare now",
    comparePageEyebrow: "Mizan compare",
    comparePageTitle: "Compare properties",
    comparePageLead: "Side-by-side view of price, size, and key facts — decide before you contact anyone.",
    compareNeedTwo: "Select two listings on the homepage to compare them here.",
    compareLoadError: "Could not load one or both listings.",
    compareModeWarning: "You are comparing a rental with a sale listing — prices may not be directly comparable.",
    compareAttribute: "Attribute",
    compareColumnA: "Listing A",
    compareColumnB: "Listing B",
    compareRowMode: "Listing type",
    compareRowHmlo: "Price guidance (HMLO)",
    compareYes: "Yes",
    compareNo: "No",
    comparePickOthers: "Compare other listings",
    detailAddCompare: "Add to compare",
    detailInCompare: "In compare",
    language: "Language",
    hmloHigh: "High",
    hmloMedium: "Medium",
    hmloLow: "Low",
    hmloOpportunity: "Opportunity",
    hmloTitle: "Price guidance vs neighborhood",
    confirmListing: "Confirm listing is still active",
    leaveReview: "Leave a review",
    suppliers: "Related services",
    holisticServicesTitle: "Your bridge to trusted property experts",
    holisticServicesLead: "Choose what you need help with and we'll connect you with the right specialist.",
    holisticServicesNoWhatsApp: "WhatsApp is not configured — use Contact for now.",
    requestExpertHelp: "Request expert help",
    forSale: "For Sale",
    forRent: "For Rent",
    categoryResidential: "Residential",
    categoryCommercial: "Commercial",
    categoryLand: "Land",
    typeApartmentCondo: "Apartment / Condo",
    typeVillaHouse: "Villa / House",
    typeStudio: "Studio",
    typeRoom: "Room",
    typeOffice: "Office",
    typeShopRetail: "Shop / Retail",
    typeCommercialBuilding: "Commercial Building",
    typeHotel: "Hotel",
    typeWarehouse: "Warehouse",
    typeResidentialLand: "Residential Land",
    typeCommercialLand: "Commercial Land",
    typeAgriculturalLand: "Agricultural Land",
    loginAccount: "Account",
    loginTitle: "Sign in",
    loginLead: "Use your email and password to access your Market Mizan account.",
    loginCreateAccount: "Create account",
    loginEmail: "Email",
    loginPassword: "Password",
    loginRememberMe: "Remember me",
    loginForgotPassword: "Forgot password?",
    loginPleaseWait: "Please wait…",
    loginFailed: "Login failed.",
    registerFailed: "Registration failed.",
    loginShowPassword: "Show password",
    loginHidePassword: "Hide password",
    loginEnterPassword: "Enter your password",
    loginCreatePassword: "Create a password",
    loginRegisterRole: "Account type",
    loginAccountMode: "Account mode",
    emailPlaceholder: "name@example.com",
    loginRegisterRoleStandard: "Buyer / tenant (standard)",
    loginRegisterRoleLandlord: "Private landlord",
    loginRegisterRoleAgency: "Agency / broker",
    reviewsTitle: "Reviews",
    reviewsLead: "Share your experience with this listing or neighborhood.",
    reviewsEmpty: "No reviews yet — be the first to share your thoughts.",
    reviewsCount: "review(s)",
    reviewEmail: "Your email *",
    reviewRating: "Rating",
    reviewComment: "Comment",
    reviewStars: "{n} stars",
    reviewSubmit: "Submit review",
    reviewThanks: "Thank you for your review.",
    reviewError: "Could not submit review.",
    contactUs: "Contact us",
    contactUsWhatsApp: "Contact us on WhatsApp",
    contactPanelLead: "Questions about this property? We are happy to help.",
    whatsapp: "WhatsApp",
    footerLead: "Your property aggregator for Addis Ababa — clear listings, one calm place to browse.",
    trustSection: "Why Market Mizan",
    trustCompare: "Compare in one place",
    trustCompareSub: "Listings from trusted Ethiopian portals — side by side.",
    trustSource: "Original source linked",
    trustSourceSub: "Every listing links back to the broker platform.",
    trustVerify: "Community verification",
    trustVerifySub: "Confirm listings and see verified badges.",
    priceOnRequest: "Price on request",
    lastSynced: "Updated {date}",
    unverifiedNotice: "Aggregated listing – our bridge to international experts, what do you need?",
    viewOnSource: "View on {source}",
    footerExplore: "Explore",
    footerLegal: "Legal",
    footerListYourProperty: "List your property",
    footerContact: "Contact",
    footerSitemap: "Sitemap",
    footerPrivacyPolicy: "Privacy policy",
    footerTermsOfUse: "Terms of use",
    footerLegalNotice: "Legal notice (Imprint)",
    footerPrivacyShort: "Privacy",
    footerTermsShort: "Terms",
    footerImprint: "Imprint",
    footerLocation: "Addis Ababa, Ethiopia",
    footerHomeAria: "Market Mizan home",
    loadingProperty: "Loading property…",
    backToListings: "← Back to listings",
    detailPrice: "Price",
    detailPricePerSqm: "Price / m²",
    detailPriceGuidance: "Price guidance",
    detailObjectType: "Object type",
    detailStatus: "Status",
    detailSource: "Source:",
    detailLandArea: "Land area",
    detailFeatures: "Features",
    detailNoFeatures: "No features listed.",
    detailNoDescription: "No description available.",
    detailSpecifications: "Specifications",
    detailLocation: "Location",
    detailSimilarListings: "Similar listings",
    detailFloor: "Floor",
    detailGarageSpaces: "Garage spaces",
    detailArea: "Area",
    detailDistrict: "District",
    detailCity: "City",
    detailPriceHistory: "Price history",
    detailRequestRemoval: "Request removal of this listing",
    detailLastSynced: "Last synced to Market Mizan",
    detailUsdConversion: "USD conversion",
    detailListingUpdated: "Listing details updated (RealEthio)",
    detailListingUpdatedNa: "Not available — run the scraper once so we can store the \"Updated on …\" line from the listing.",
    detailFxRate: "ETB rate as of {date}",
    detailPropertyId: "Property ID",
    detailListingUpdatedSource: "Listing updated (source site)",
    detailAdminAiPreview: "Admin preview: AI summary",
    closeContactForm: "Close contact form",
    sourcePlatform: "source platform",
    contactSubject: "Subject",
    contactReference: "Reference / Title",
    contactFirstName: "First name",
    contactLastName: "Last name",
    contactEmail: "Email",
    contactPhone: "Phone number",
    contactQuestions: "Your questions",
    contactQuestionsPlaceholder: "Type your questions here…",
    contactOpeningWhatsApp: "Opening WhatsApp…",
    contactContinueWhatsApp: "Continue on WhatsApp",
    contactPropertyInquiry: "Property inquiry",
    contactWhatsAppNotConfigured: "WhatsApp is not configured. Please contact us via the Contact page.",
    filtersTitle: "Filters",
    filterListingMode: "Listing mode",
    filterMinPrice: "Min price",
    filterMaxPrice: "Max price",
    filterType: "Type",
    filterArea: "Area",
    filterSource: "Source",
    filterReset: "Reset",
    filterAll: "All",
    moreFiltersTitle: "More filters",
    moreFiltersLead: "Refine your search by price, size, and other criteria. Changes apply to the listings below.",
    moreFiltersPrice: "Price (ETB)",
    moreFiltersMinPrice: "Min price",
    moreFiltersMaxPrice: "Max price",
    moreFiltersPricePlaceholder: "0 ETB",
    moreFiltersSize: "Size (m²)",
    moreFiltersMinSize: "Min size",
    moreFiltersMaxSize: "Max size",
    moreFiltersSizePlaceholder: "0 m²",
    moreFiltersBathrooms: "Bathrooms (min.)",
    moreFiltersBedrooms: "Bedrooms (min.)",
    resetAllFilters: "Reset all filters",
    applyFilters: "Apply filters",
    clearExtraFilters: "Clear extra filters",
    cancel: "Cancel",
    apply: "Apply",
    filterAny: "Any",
    supplierPropertyManagement: "Property management",
    supplierPropertyManagementDesc: "Tenant support, maintenance coordination, rent handling",
    supplierInteriorDesign: "Interior design",
    supplierInteriorDesignDesc: "Staging, furnishing, renovation guidance",
    supplierCraftsmanship: "Craftsmanship",
    supplierCraftsmanshipDesc: "Repairs, finishing, and build-out support",
    supplierMortgage: "Mortgage / bank",
    supplierMortgageDesc: "Financing support and bank introductions",
    supplierInsurance: "Insurance",
    supplierInsuranceDesc: "Property coverage and risk protection",
    paginationLabel: "Pagination",
    paginationPrev: "Previous page",
    paginationNext: "Next page",
    paginationPage: "Page {n}",
    confirmListingButton: "✔ Confirm this listing is still active",
    confirmListingEmail: "Your email *",
    confirmListingClose: "Close",
    confirmListingSubmit: "Confirm",
    confirmListingThanks: "Thank you! {count} confirmation(s) recorded.",
    confirmListingError: "Could not confirm.",
    removalTitle: "Request removal of this listing",
    removalLead: "If you are the owner or agent, tell us why this listing should be removed.",
    removalEmail: "Your email",
    removalReason: "Reason",
    removalSending: "Sending…",
    removalSubmit: "Submit request",
    removalSuccess: "Your removal request was sent. We will review it shortly.",
    removalError: "Could not send request. Please try again.",
    whatsappFabLabel: "WhatsApp",
    contactFabLabel: "Contact",
    whatsappFabMessage: "Hello Market Mizan — I have a question about a listing.",
    contactPageEyebrow: "Contact",
    contactPageTitle: "We are here to help",
    contactPageLead: "Questions about listings, partnerships, or your account — send a message and we will respond as soon as we can.",
    contactPageSendMessage: "Send a message",
    contactPagePrivacyNote: "Fields marked by the form are required where applicable. We treat your data confidentially.",
    contactPageSuccess: "Thank you — your message has been sent. We will get back to you soon.",
    contactPageSendAnother: "Send another message",
    contactPhoneOptional: "Phone (optional)",
    contactMessage: "Message",
    contactSending: "Sending…",
    contactSendMessage: "Send message",
    contactPageVisit: "Visit",
    contactPageHours: "Hours",
    contactPageHoursValue: "Mon–Fri 09:00–18:00\nSat 09:00–14:00",
    contactPageMapLabel: "Map of Addis Ababa",
    contactPageMapTitle: "Addis Ababa map",
    contactPageMapLocation: "Addis Ababa, Ethiopia",
    contactFirstNamePlaceholder: "Enter your first name",
    contactLastNamePlaceholder: "Enter your last name",
    contactEmailPlaceholder: "you@example.com",
    contactPhonePlaceholder: "+251 …",
    contactMessagePlaceholder: "Type your message here…",
    contactPageError: "Could not send your message. Please try again or email us directly.",
    navBuyOrRent: "Buy or rent",
    navMobile: "Mobile navigation",
    navSocial: "Social media",
    navLegalSub: "Legal",
    requiredStar: "*"
  },
  am: {
    heroTitle: "በሚዛን ትክክለኛውን ንብረት ለማግኘት ያግኙ",
    heroSub: "በኢትዮጵያ የንግድ ቤት ገበያ ለማወዳደር እና ለመጀመር የታመነ መድረክ",
    heroUploadCta: "ንግድዎን ይስቀሉ",
    rent: "ኪራይ",
    buy: "ግዛ",
    sell: "ሽጥ",
    findAgent: "ወኪል ፈልግ",
    manageRentals: "ኪራዮችን አስተዳድር",
    verifyListing: "ማስታወቂያህን አረጋግጥ",
    advertise: "አስተዋውቅ",
    getHelp: "እገዛ አግኝ",
    signIn: "ግባ",
    signOut: "ውጣ",
    dashboard: "ዳሽቦርድ",
    navListings: "ዝርዝሮች",
    navAbout: "ስለ እኛ",
    navMap: "ካርታ",
    navUpload: "ዝርዝር ስቀል",
    navAdmin: "አስተዳዳሪ",
    navLogin: "ግባ",
    navAccount: "መለያ",
    navLogout: "ውጣ",
    menu: "ምናሌ",
    closeMenu: "ምናሌ ዝጋ",
    openMenu: "ምናሌ ክፈት",
    searchBuy: "ግዛ",
    searchRent: "ኪራይ",
    searchForRent: "ለኪራይ",
    searchForSale: "ለሽያጭ",
    searchPlaceholder: "በአካባቢ ወይም ቁልፍ ቃል ፈልግ",
    searchType: "አይነት",
    searchCity: "ከተማ",
    searchArea: "አካባቢ",
    searchBedrooms: "መኝታ ክፍሎች",
    searchSubmit: "ፈልግ",
    moreFilters: "ተጨማሪ ማጣሪያዎች",
    popularSearches: "ተወዳጅ ፍለጋዎች",
    quickFilter1: "አፓርታማ · ቦሌ",
    quickFilter2: "2 መኝታ · ለኪራይ",
    quickFilter3: "ቪላ · ለሽያጭ",
    quickFilter4: "ንግድ · ካዛንቺስ",
    quickFilter5: "ስቱዲዮ · ከ ETB 50k ያነሰ",
    properties: "ንብረቶች",
    listingsCount: "ማስታወቂያዎች",
    loadingListings: "ዝርዝሮች በመጫን ላይ…",
    sort: "ደርድር",
    sortRecommended: "የተመከሩ",
    sortLatest: "አዲስ",
    sortPriceAsc: "ዋጋ፦ ከዝቅተኛ ወደ ከፍተኛ",
    sortPriceDesc: "ዋጋ፦ ከከፍተኛ ወደ ዝቅተኛ",
    sortSize: "ስፋት",
    showingPerPage: "በገጽ {n}",
    pageOf: "ገጽ {page} ከ {total}",
    noListingsTitle: "ምንም ዝርዝር አልተገኘም",
    noListingsBody: "በግዛ/ኪራይ ለውጥ፣ ማጣሪያዎችን ያጽዱ ወይም አዲስ ስክራይ መስራት ይሞክሩ።",
    recommendations: "ለእርስዎ የተመከሩ",
    recommendationsSub: "የተመረጡ ዝርዝሮች — ወደ ውሳኔ በአንድ ጠባብ መንገድ።",
    verified: "የተረጋገጠ",
    newBadge: "አዲስ",
    bedrooms: "መኝታ ክፍሎች",
    beds: "መኝታ ክፍሎች",
    baths: "መታጠቢያ ቤቶች",
    livingArea: "የመኖሪያ ስፋት",
    furnishedLabel: "የተዘጋጀ",
    furnishedYes: "አዎ",
    furnishedNo: "አይ",
    monthlyRentSuffix: "ወራዊ ኪራይ",
    saleSuffix: "ሽያጭ",
    salePrice: "የሽያጭ ዋጋ",
    rentPrice: "ኪራይ",
    noPhoto: "ፎቶ የለም",
    cardDisclaimer: "ሁሉም ዝርዝሮች የራሳቸው መድረኮች ({source}) ናቸው።",
    viewDetails: "ዝርዝር ተመልከት",
    compareMode: "አወዳድር",
    compareModeActive: "መምረጥ…",
    compareModeHint: "ለማወዳደር 2 ዝርዝሮች ይምረጡ።",
    compareAdd: "ለማወዳደር ጨምር",
    compareRemove: "ከማወዳደር አስወግድ",
    compareSelected: "ለማወዳደር ተመርጧል",
    compareTrayLabel: "የማወዳደር ምርጫ",
    compareTrayTitle: "{count} ከ {max} ተመርጧል",
    compareSlotEmpty: "ዝርዝር ይምረጡ",
    compareClear: "አጽዳ",
    compareExit: "ውጣ",
    compareCta: "አሁን አወዳድር",
    comparePageEyebrow: "Mizan ማወዳደር",
    comparePageTitle: "ንግድ ቤቶችን አወዳድር",
    comparePageLead: "ዋጋ፣ መጠን እና ዋና መረጃዎች በጎን ለጎን — ከመገናኘትዎ በፊት ይወስኑ።",
    compareNeedTwo: "እዚህ ለማወዳደር በመነሻ ገጽ ላይ 2 ዝርዝሮች ይምረጡ።",
    compareLoadError: "አንድ ወይም ሁለቱን ዝርዝሮች ማምጣት አልተቻለም።",
    compareModeWarning: "ኪራይ ከሽያጭ ጋር እያወዳደሩ ነው — ዋጋዎች ሊተሳሰሩ ይችላሉ።",
    compareAttribute: "ባህሪ",
    compareColumnA: "ዝርዝር አ",
    compareColumnB: "ዝርዝር ቢ",
    compareRowMode: "የዝርዝር አይነት",
    compareRowHmlo: "የዋጋ መመሪያ (HMLO)",
    compareYes: "አዎ",
    compareNo: "አይ",
    comparePickOthers: "ሌሎች ዝርዝሮች አወዳድር",
    detailAddCompare: "ለማወዳደር ጨምር",
    detailInCompare: "በማወዳደር ውስጥ",
    language: "ቋንቋ",
    hmloHigh: "ከፍ",
    hmloMedium: "መካከለኛ",
    hmloLow: "ዝቅ",
    hmloOpportunity: "እድል",
    hmloTitle: "ዋጋ መመሪያ ከአካባቢ ጋር",
    confirmListing: "ዝርዝሩ አሁንም ገበያ ላይ መሆኑን ያረጋግጡ",
    leaveReview: "ግምገማ ይስጡ",
    suppliers: "ተዛማጅ አገልግሎቶች",
    holisticServicesTitle: "ወደ ታማኝ የንብረት ባለሙያዎች የሚያገናኝዎ መንገድ",
    holisticServicesLead: "የሚፈልጉትን እገዛ ይምረጡ፣ እኛም ከተገቢው ባለሙያ ጋር እናገናኝዎታለን።",
    holisticServicesNoWhatsApp: "WhatsApp አልተዋቀረም — ለጊዜው Contact ገጽ ይጠቀሙ።",
    requestExpertHelp: "የባለሙያ እገዛ ጠይቅ",
    forSale: "ለሽያጭ",
    forRent: "ለኪራይ",
    categoryResidential: "የመኖሪያ",
    categoryCommercial: "የንግድ",
    categoryLand: "መሬት",
    typeApartmentCondo: "አፓርታማ / ኮንዶ",
    typeVillaHouse: "ቪላ / ቤት",
    typeStudio: "ስቱዲዮ",
    typeRoom: "ክፍል",
    typeOffice: "ቢሮ",
    typeShopRetail: "ሱቅ / Retail",
    typeCommercialBuilding: "የንግድ ህንፃ",
    typeHotel: "ሆቴል",
    typeWarehouse: "መጋዘን",
    typeResidentialLand: "የመኖሪያ መሬት",
    typeCommercialLand: "የንግድ መሬት",
    typeAgriculturalLand: "የግብርና መሬት",
    loginAccount: "መለያ",
    loginTitle: "ግባ",
    loginLead: "የ Market Mizan መለያዎን ለመጠቀም ኢሜልዎን እና የይለፍ ቃልዎን ይጠቀሙ።",
    loginCreateAccount: "መለያ ፍጠር",
    loginEmail: "ኢሜል",
    loginPassword: "የይለፍ ቃል",
    loginRememberMe: "አስታውሰኝ",
    loginForgotPassword: "የይለፍ ቃል ረሱ?",
    loginPleaseWait: "እባክዎ ይጠብቁ…",
    loginFailed: "መግባት አልተሳካም።",
    registerFailed: "ምዝገባ አልተሳካም።",
    loginShowPassword: "የይለፍ ቃል አሳይ",
    loginHidePassword: "የይለፍ ቃል ደብቅ",
    loginEnterPassword: "የይለፍ ቃልዎን ያስገቡ",
    loginCreatePassword: "የይለፍ ቃል ፍጠር",
    loginRegisterRole: "የመለያ አይነት",
    loginAccountMode: "የመለያ ሁነታ",
    emailPlaceholder: "name@example.com",
    loginRegisterRoleStandard: "ገዢ / ተከራይ (መደበኛ)",
    loginRegisterRoleLandlord: "ግል ባለቤት",
    loginRegisterRoleAgency: "ወኪል / broker",
    reviewsTitle: "ግምገማዎች",
    reviewsLead: "ስለዚህ ዝርዝር ወይም አካባቢ ተሞክሮዎን ያካፍሉ።",
    reviewsEmpty: "ግምገማ የለም — የመጀመሪያው ይሁኑ።",
    reviewsCount: "ግምገማ(ዎች)",
    reviewEmail: "ኢሜልዎ *",
    reviewRating: "ደረጃ",
    reviewComment: "አስተያየት",
    reviewStars: "{n} ኮከብ",
    reviewSubmit: "ግምገማ ይላኩ",
    reviewThanks: "ለግምገማዎ እናመሰግናለን።",
    reviewError: "ግምገማ መላክ አልተቻለም።",
    contactUs: "አግኙን",
    contactUsWhatsApp: "በ WhatsApp ያግኙን",
    contactPanelLead: "ስለዚህ ንግድ ቤት ጥያቄ አለዎት? እናገርዎታለን።",
    whatsapp: "WhatsApp",
    footerLead: "የአዲስ አበባ ንግድ ቤት-aggregator — ግልጽ ዝርዝሮች በአንድ ቦታ።",
    trustSection: "ለምን Market Mizan",
    trustCompare: "በአንድ ቦታ ያወዳድሩ",
    trustCompareSub: "ከታመኑ የኢትዮጵያ መድረኮች ዝርዝሮች በአንድ ቦታ.",
    trustSource: "ዋናው መድረክ ተገናኝቷል",
    trustSourceSub: "ሁሉም ዝርዝር ወደ ወኪል መድረክ ይያያዋል.",
    trustVerify: "የማህበረሰብ ማረጋገጫ",
    trustVerifySub: "ዝርዝሮችን ያረጋግጡ እና የተረጋገጡ ምልክቶችን ይመልከቱ.",
    priceOnRequest: "ዋጋ በጥያቄ",
    lastSynced: "ተዘምኗል {date}",
    unverifiedNotice: "የተሰብሰበ ዝርዝር — ወደ ዓለም አቀፍ ባለሙያዎች ድልድይዎ፣ ምን ይፈልጋሉ?",
    viewOnSource: "በ{source} ላይ ይመልከቱ",
    footerExplore: "ያስሱ",
    footerLegal: "ህጋዊ",
    footerListYourProperty: "ንግድዎን ይዘርዝሩ",
    footerContact: "አግኙን",
    footerSitemap: "የገጽ ካርታ",
    footerPrivacyPolicy: "የግላዊነት ፖሊሲ",
    footerTermsOfUse: "የአጠቃቀም ውሎች",
    footerLegalNotice: "ህጋዊ ማስታወቂያ",
    footerPrivacyShort: "ግላዊነት",
    footerTermsShort: "ውሎች",
    footerImprint: "ማስታወቂያ",
    footerLocation: "አዲስ አበባ፣ ኢትዮጵያ",
    footerHomeAria: "Market Mizan መነሻ",
    loadingProperty: "ንግድ ቤት በመጫን ላይ…",
    backToListings: "ወደ ማስታወቂያዎች ተመለስ",
    detailPrice: "ዋጋ",
    detailPricePerSqm: "ዋጋ / m²",
    detailPriceGuidance: "የዋጋ መመሪያ",
    detailObjectType: "የንብረት አይነት",
    detailStatus: "ሁኔታ",
    detailSource: "ምንጭ:",
    detailLandArea: "የመሬት ስፋት",
    detailFeatures: "ባህሪያት",
    detailNoFeatures: "ባህሪያት አልተዘረዘሩም።",
    detailNoDescription: "መግለጫ የለም።",
    detailSpecifications: "ዝርዝር መግለጫ",
    detailLocation: "አካባቢ",
    detailSimilarListings: "ተመሳሳይ ዝርዝሮች",
    detailFloor: "ወለል",
    detailGarageSpaces: "ጋራዥ ቦታ",
    detailArea: "አካባቢ",
    detailDistrict: "ወረዳ",
    detailCity: "ከተማ",
    detailPriceHistory: "የዋጋ ታሪክ",
    detailRequestRemoval: "ይህን ዝርዝር ለማስወገድ ጥያቄ",
    detailLastSynced: "ወደ Market Mizan የመጨረሻ ስንክ",
    detailUsdConversion: "USD ቅድመ ማስላት",
    detailListingUpdated: "የዝርዝር ዝመና (RealEthio)",
    detailListingUpdatedNa: "የለም — \"Updated on …\" መስመር ለመያዝ ስክራይፐር አንድ ጊዜ ያስኬዱ።",
    detailFxRate: "ETB ተመን ከ {date}",
    detailPropertyId: "የንብረት መለያ",
    detailListingUpdatedSource: "ዝርዝር ተዘምኗል (ምንጭ)",
    detailAdminAiPreview: "አስተዳዳሪ: AI ማጠቃለያ",
    closeContactForm: "የእውቂያ ቅጽ ዝጋ",
    sourcePlatform: "ምንጭ መድረክ",
    contactSubject: "ርዕስ",
    contactReference: "ማጣቀሻ / ርዕስ",
    contactFirstName: "ስም",
    contactLastName: "የአባት ስም",
    contactEmail: "ኢሜል",
    contactPhone: "ስልክ",
    contactQuestions: "ጥያቄዎ",
    contactQuestionsPlaceholder: "ጥያቄዎን እዚህ ይፃፉ…",
    contactOpeningWhatsApp: "WhatsApp በመክፈት ላይ…",
    contactContinueWhatsApp: "በ WhatsApp ይቀጥሉ",
    contactPropertyInquiry: "የንግድ ቤት ጥያቄ",
    contactWhatsAppNotConfigured: "WhatsApp አልተዋቀረም — Contact ገጽ ይጠቀሙ።",
    filtersTitle: "ማጣሪያዎች",
    filterListingMode: "የዝርዝር ሁኔታ",
    filterMinPrice: "ዝቅተኛ ዋጋ",
    filterMaxPrice: "ከፍተኛ ዋጋ",
    filterType: "አይነት",
    filterArea: "አካባቢ",
    filterSource: "ምንጭ",
    filterReset: "ዳግም አስጀምር",
    filterAll: "ሁሉም",
    moreFiltersTitle: "ተጨማሪ ማጣሪያ",
    moreFiltersLead: "በዋጋ፣ ስፋት እና ሌሎች መስፈርቶች ያጣሩ። ለታች ያለው ዝርዝር ይተገብራል።",
    moreFiltersPrice: "ዋጋ (ETB)",
    moreFiltersMinPrice: "ዝቅተኛ ዋጋ",
    moreFiltersMaxPrice: "ከፍተኛ ዋጋ",
    moreFiltersPricePlaceholder: "0 ETB",
    moreFiltersSize: "መጠን (m²)",
    moreFiltersMinSize: "ዝቅተኛ መጠን",
    moreFiltersMaxSize: "ከፍተኛ መጠን",
    moreFiltersSizePlaceholder: "0 m²",
    moreFiltersBathrooms: "መታጠቢያ (አነስ.)",
    moreFiltersBedrooms: "መኝታ (አነስ.)",
    resetAllFilters: "ሁሉንም ማጣሪያዎች ዳግም አስጀምር",
    applyFilters: "ማጣሪያዎችን ተግብር",
    clearExtraFilters: "ተጨማሪ ማጣሪያ አጽዳ",
    cancel: "ሰርዝ",
    apply: "ተግብር",
    filterAny: "ማንኛውም",
    supplierPropertyManagement: "የንብረት አስተዳደር",
    supplierPropertyManagementDesc: "ኪራይ እና ጥገና ድጋፍ",
    supplierInteriorDesign: "የውስጥ ዲዛይን",
    supplierInteriorDesignDesc: "Staging እና renovation",
    supplierCraftsmanship: "እደ-ጥበቃ",
    supplierCraftsmanshipDesc: "ጥገና እና construction",
    supplierMortgage: "Mortgage / ባንክ",
    supplierMortgageDesc: "የ-financing አማራጮች",
    supplierInsurance: "Insurance",
    supplierInsuranceDesc: "የንብረት መድን",
    paginationLabel: "ገጽ መቀየሪያ",
    paginationPrev: "ቀዳሚ ገጽ",
    paginationNext: "ቀጣይ ገጽ",
    paginationPage: "ገጽ {n}",
    confirmListingButton: "✔ ይህ ዝርዝር አሁንም ገበያ ላይ መሆኑን ያረጋግጡ",
    confirmListingEmail: "ኢሜልዎ *",
    confirmListingClose: "ዝጋ",
    confirmListingSubmit: "አረጋግጥ",
    confirmListingThanks: "አመሰግናለሁ! {count} ማረጋገጫ(ዎች) ተመዝግቧል።",
    confirmListingError: "ማረጋገጥ አልተቻለም።",
    removalTitle: "ይህን ዝርዝር ለማስወገድ ጥያቄ",
    removalLead: "ባለቤት ወይም ወኪል ከሆኑ፣ ይህ ዝርዝር ለምን መወገድ እንዳለበት ይግለጹ።",
    removalEmail: "ኢሜልዎ",
    removalReason: "ምክንያት",
    removalSending: "በመላክ ላይ…",
    removalSubmit: "ጥያቄ ላክ",
    removalSuccess: "የማስወገድ ጥያቄዎ ተልኳል። በቅርቡ እንመለከታለን።",
    removalError: "ጥያቄ መላክ አልተቻለም። እንደገና ይሞክሩ።",
    whatsappFabLabel: "WhatsApp",
    contactFabLabel: "አግኙን",
    whatsappFabMessage: "ሰላም Market Mizan — ስለ ዝርዝር ጥያቄ አለኝ።",
    contactPageEyebrow: "አግኙን",
    contactPageTitle: "እዚህ ነን ለመርዳት",
    contactPageLead: "ስለ ዝርዝሮች፣ ትብብር ወይም መለያ — መልእክት ይላኩ እና በተቻለ ፍጥነት እንመልሳለን።",
    contactPageSendMessage: "መልእክት ላክ",
    contactPagePrivacyNote: "የሚያስፈልጉ መስኮች በቅጽ ላይ ተመልክተዋል። መረጃዎን በሚስጥር እንይዛለን።",
    contactPageSuccess: "አመሰግናለሁ — መልእክትዎ ተልኳል። በቅርቡ እንመልሳለን።",
    contactPageSendAnother: "ሌላ መልእክት ላክ",
    contactPhoneOptional: "ስልክ (አማራጭ)",
    contactMessage: "መልእክት",
    contactSending: "በመላክ ላይ…",
    contactSendMessage: "መልእክት ላክ",
    contactPageVisit: "ይጎብኙን",
    contactPageHours: "ሰዓት",
    contactPageHoursValue: "ሰኞ–አርብ 09:00–18:00\nቅዳ 09:00–14:00",
    contactPageMapLabel: "የአዲስ አበባ ካርታ",
    contactPageMapTitle: "የአዲስ አበባ ካርታ",
    contactPageMapLocation: "አዲስ አበባ፣ ኢትዮጵያ",
    contactFirstNamePlaceholder: "የመጀመሪያ ስምዎን ያስገቡ",
    contactLastNamePlaceholder: "የአባት ስምዎን ያስገቡ",
    contactEmailPlaceholder: "you@example.com",
    contactPhonePlaceholder: "+251 …",
    contactMessagePlaceholder: "መልእክትዎን እዚህ ይፃፉ…",
    contactPageError: "መልእክት መላክ አልተቻለም። እንደገና ይሞክሩ ወይም በኢሜል ያግኙን።",
    navBuyOrRent: "ግዛ ወይም ኪራይ",
    navMobile: "የሞባይል መራመጃ",
    navSocial: "ማህበራዊ ሚዲያ",
    navLegalSub: "ህጋዊ",
    requiredStar: "*"
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const stored = localStorage.getItem("mmizan_lang");
    return stored === "am" ? "am" : "en";
  });

  useEffect(() => {
    document.documentElement.lang = lang === "am" ? "am" : "en";
  }, [lang]);

  const t = useMemo(() => {
    const dict = STRINGS[lang] || STRINGS.en;
    return (key, vars) => {
      let text = dict[key] || STRINGS.en[key] || key;
      if (vars) {
        Object.entries(vars).forEach(([k, v]) => {
          text = text.replace(`{${k}}`, String(v));
        });
      }
      return text;
    };
  }, [lang]);

  function setLanguage(next) {
    const safe = next === "am" ? "am" : "en";
    setLang(safe);
    localStorage.setItem("mmizan_lang", safe);
    document.documentElement.lang = safe === "am" ? "am" : "en";
  }

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage requires LanguageProvider");
  return ctx;
}

export function LanguageToggle({ compact = false }) {
  const { lang, setLanguage, t } = useLanguage();
  return (
    <div
      className={`inline-flex rounded-lg border border-line bg-surface p-0.5${compact ? " text-xs" : ""}`}
      role="group"
      aria-label={t("language")}
    >
      <button
        type="button"
        className={`rounded-md px-2 py-1 font-medium transition-colors${lang === "en" ? " bg-primary text-white" : " text-muted hover:text-primary"}`}
        onClick={() => setLanguage("en")}
        aria-pressed={lang === "en"}
      >
        EN
      </button>
      <button
        type="button"
        className={`rounded-md px-2 py-1 font-medium transition-colors${lang === "am" ? " bg-primary text-white" : " text-muted hover:text-primary"}`}
        onClick={() => setLanguage("am")}
        aria-pressed={lang === "am"}
      >
        አማ
      </button>
    </div>
  );
}
